MacGym_WebRole/Models/IndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MacGym_DB;

namespace MacGym_WebRole.Models
{
    public class IndexModel
    {
        public List<ToolModel> Tools { get; set; }
        public List<BodyPart> BodyParts { get; set; }
        public List<Workout> LastViewed { get; set; }
    }
}

MacGym_WebRole/Models/ListModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MacGym_DB;

namespace MacGym_WebRole.Models
{
    public class ListModel
    {
        public List<WorkoutModel> Workouts { get; set; }
    }
}

MacGym_WebRole/Models/ToolModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MacGym_DB;

namespace MacGym_WebRole.Models
{
    public class ToolModel
    {
        private Tool _tool = null;
        public ToolModel(Tool tool)
        {
            _tool = tool;
        }

        public bool HasImage
        {
            get
            {
                return _tool.ToolImages.Count() > 0;
            }
        }

        public string FirstImage
        {
            get
            {
                return _tool.ToolImages.Count() > 0 ? _tool.ToolImages.FirstOrDefault().image : null;
            }
        }

        public List<string> Images
        {
            get
            {
                return _tool.ToolImages.Select(i => i.image).ToList();
            }
        }

        public int ToolID
        {
            get
            {
                return _tool.toolID;
            }
        }

        public string Name
        {
            get
            {
                return _tool.name;
            }
        }
    }
}

MacGym_WebRole/Models/WorkoutModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MacGym_DB;

namespace MacGym_WebRole.Models
{
    public class WorkoutModel
    {
        private Workout _workout = null;
        public WorkoutModel(Workout workout)
        {
            _workout = workout;
        }

        public bool HasImage
        {
            get
            {
                return _workout.WorkoutImages.Count() > 0;
            }
        }

        public string FirstImage
        {
            get
            {
                return _workout.WorkoutImages.Count() > 0 ? _workout.WorkoutImages.FirstOrDefault().image : null;
            }
        }

        public List<string> Images
        {
            get
            {
                return _workout.WorkoutImages.Select(i => i.image).ToList();
            }
        }

        public bool HasVideo
        {
            get
            {
                return false;
            }
        }

        public bool HasAudio
        {
            get
            {
                return false;
            }
        }

        public int WorkoutID
        {
            get
            {
                return _workout.workoutID;
            }
        }

        public string Description
        {
            get
            {
                return _workout.description;
            }
        }

        public string Name
        {
            get
            {
                return _workout.name;
            }
        }

        public List<BodyPart> BodyParts { get; set; }
        public List<Tool> Tools { get; set; }
    }
}

MacGym_WebRole/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MacGym_WebRole.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

MacGym_WebRole/Controllers/WorkoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MacGym_DB;
using MacGym_WebRole.Models;

namespace MacGym_WebRole.Controllers
{
    public class WorkoutController : Controller
    {
        public ActionResult Index()
        {
            IndexModel model = new IndexModel();
            model.Tools = new ToolsRepository().Get().Select(t => new ToolModel(t)).ToList();
            model.BodyParts = new BodyPartsRepository().Get();
            model.LastViewed = new WorkoutsRepository().GetLastViewed(10);
            return View(model);
        }

        public ActionResult Details(int id)
        {
            new WorkoutsRepository().AddView(id);

            WorkoutModel model = new WorkoutModel(new WorkoutsRepository().Get(id));
            model.BodyParts = new BodyPartsRepository().GetByWorkout(id);
            model.Tools = new ToolsRepository().GetByWorkout(id);
            return View(model);
        }

        public ActionResult List(int? tool, int? bodyPart, string search)
        {
            ListModel model =  new ListModel();
            if (!string.IsNullOrWhiteSpace(search))
            {
                model.Workouts = new WorkoutsRepository().Get(search).Select(w => new WorkoutModel(w)).ToList();
            }
            else
            {
                model.Workouts = new WorkoutsRepository().Get(tool.HasValue ? tool.Value : 0, bodyPart.HasValue ? bodyPart.Value : 0).Select(w => new WorkoutModel(w)).ToList();
            }
            return View(model);
        }

        public ActionResult Search(string searchText)
        {
            return RedirectToActionPermanent("List", new { search = searchText });
        }
    }
}

MacGym_WebRole/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}
@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#myTab').tab();

            $('#myTab a').click(function (e) {
                e.preventDefault();
                $(this).tab('show');
            })
        });


    </script>
}
<div class="row">
    <div class="span9">
        
        
        
        <ul class="nav nav-tabs" id="myTab">
            <li class="active"><a href="#home">Home</a></li>
            <li><a href="#profile">Profile</a></li>
            <li><a href="#messages">Messages</a></li>
            <li><a href="#settings">Settings</a></li>
        </ul>
 
        <div class="tab-content">
            <div class="tab-pane active" id="home">t</div>
            <div class="tab-pane" id="profile">g</div>
            <div class="tab-pane" id="messages">h</div>
            <div class="tab-pane" id="settings">j</div>
        </div>



    </div>
    <div class="span3">
        <h4>Last 10 viewed</h4>
        <ul>
            <li><a href="#">text 1</a></li>
            <li><a href="#">text 2</a></li>
            <li><a href="#">text 3</a></li>
            <li><a href="#">text 4</a></li>
            <li><a href="#">text 5</a></li>
            <li><a href="#">text 6</a></li>
            <li><a href="#">text 7</a></li>
            <li><a href="#">text 8</a></li>
            <li><a href="#">text 9</a></li>
            <li><a href="#">text 10</a></li>
        </ul>
    </div>
</div>

MacGym_WebRole/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <title>@ViewBag.Title - MacGym</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/styles/css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
        body
        {
            padding-top: 60px;
            padding-bottom: 40px;
        }
    </style>
    <link href="~/styles/css/bootstrap-responsive.css" rel="stylesheet">
    @Styles.Render("~/styles/css")
    @Styles.Render("~/styles/less")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required:false)
</head>

<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MacGym", "Index", null, new { @class = "brand" })
                <div class="nav-collapse collapse">
                    @using (@Html.BeginForm("Search", "Workout", FormMethod.Post, new { @class = "navbar-form pull-right" }))
                    {
                        <input class="span2" placeholder="Search by keyword" type="text" name="searchText">
                        <button type="submit" class="btn">Search</button>
                    }
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        @RenderBody()
        <hr>
        <footer>
            <p>&copy; Macadamian 2013</p>
        </footer>
    </div>
</body>

</html>

MacGym_WebRole/Views/Workout/Details.cshtml
@model WorkoutModel
@{
    ViewBag.Title = "Details";
}
@section scripts
{
    @Scripts.Render("~/lightbox")
}
<h2>@Model.Name</h2>

<hr>

@if(Model.HasImage)
{
    <h4 class="detail-title">Photos</h4>
    <div class="row">
        @foreach (var item in Model.Images)
        {
            <div class="span2 gallery-img">
                <a href="~/Content/Images/Workouts/@(item)" rel="lightbox[plants]"><img src="~/Content/Images/Workouts/@(item)" class="thumb"></a>
            </div>
        }
    </div>
}

@if(Model.HasVideo)
{
    <h4 class="detail-title">Videos</h4>
    <div class="row">
        <div class="span2">
            <iframe width="300" height="225" src="http://www.youtube.com/embed/QtYgmDEddug" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>
}

@if(Model.HasAudio)
{
    <h4 class="detail-title">Audio Recordings</h4>
    <div class="row">
        <div class="span2">
            Not available
        </div>
    </div>
}

<h4 class="detail-title">Description</h4>
<div class="row">
    <div class="span12">
        @Html.Raw(Model.Description)
    </div>
</div>

<div class="row">
    <div class="span6">
        <h4 class="detail-title">Tools</h4>
        @foreach (var item in Model.Tools)
        {
            <p>@(Html.ActionLink(item.name, "List", new { tool = item.toolID }))</p>
        }
    </div>
    <div class="span6">
        <h4 class="detail-title">Parts of Body</h4>
        @foreach (var item in Model.BodyParts)
        {
            <p>@(Html.ActionLink(item.name, "List", new { bodyPart = item.bodyPartID }))</p>
        }        
    </div>
</div>

MacGym_WebRole/Views/Workout/Index.cshtml
@model IndexModel
@{
    ViewBag.Title = "Home";
}
@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#myTab').tab();

            $('#myTab a').click(function (e) {
                e.preventDefault();
                $(this).tab('show');
            })
        });
    </script>
}

<h2>Home</h2>

<div class="row">
    <div class="span9">
         
        <ul class="nav nav-tabs" id="myTab">
            <li class="active"><a href="#body">BODY</a></li>
            <li><a href="#tools">TOOLS</a></li>
        </ul>
 
        <div class="tab-content">
            <div class="tab-pane active" id="body">
                <div class="span3">
                    <ul>
                        @foreach (var item in Model.BodyParts)
                        {
                            <li>@(Html.ActionLink(item.name, "List", new { bodyPart = item.bodyPartID }))</li>
                        }
                    </ul>
                </div>
                <div class="span4">
                    <img src="~/images/body.png" usemap="#planetmap" class="text-center">

                    <map name="planetmap">
                        <area shape="rect" coords="115,40,145,70" href="@Url.Action("List", new { bodyPart = 2 })" title="Neck" alt="Neck">
                        <area shape="rect" coords="80,80,175,65" href="@Url.Action("List", new { bodyPart = 1 })" title="Back" alt="Back">
                        <area shape="rect" coords="0,190,85,85" href="@Url.Action("List", new { bodyPart = 3 })" title="Arm" alt="Arm">
                        <area shape="rect" coords="250,190,175,85" href="@Url.Action("List", new { bodyPart = 3 })" title="Arm" alt="Arm">
                        <area shape="rect" coords="160,180,95,120" href="@Url.Action("List", new { bodyPart = 4 })" title="Belly" alt="Belly">
                        <area shape="rect" coords="170,180,85,290" href="@Url.Action("List", new { bodyPart = 5 })" title="Thigh" alt="Thigh">
                        <area shape="rect" coords="40,190,5,230" href="@Url.Action("List", new { bodyPart = 6 })" title="Fingers" alt="Fingers">
                        <area shape="rect" coords="250,190,210,230" href="@Url.Action("List", new { bodyPart = 6 })" title="Fingers" alt="Fingers">
                    </map> 
                </div>
               
            </div>
            <div class="tab-pane" id="tools">
                <ul>
                    @foreach (var item in Model.Tools)
                    {
                        <li class="tool-thumb">
                            @if(item.HasImage)
                            {
                                <a href="@Url.Action("List", new { tool = item.ToolID })">
                                    <img src="~/Content/Images/Tools/@(item.FirstImage)" />
                                </a>
                            }
                            @(Html.ActionLink(item.Name, "List", new { tool = item.ToolID }))
                        </li>
                    }
                </ul>
            </div>
        </div>

    </div>
    @if(Model.LastViewed.Count > 0)
    {
        <div class="span3">
            <h4>Last @(Model.LastViewed.Count) viewed</h4>
            <ul>
                @foreach (var item in Model.LastViewed)
                {
                    <li>@Html.ActionLink(item.name, "Details", new { id = item.workoutID })</li>    
                }
            </ul>
        </div>
    }
    <div class="span3 banner"><h3>YOUR CREATIVITY DAY BANNER HERE</h3></div>
    <div class="span3 source-used">
        <h5>Source Sites</h5>
        <span><a href="http://www.jefit.com" target="_blank">http://www.jefit.com</a></span><br>
        <span><a href="http://www.fitnessmagazine.com" target="_blank">http://www.fitnessmagazine.com</a></span><br>
        <span><a href="http://exercise.about.com" target="_blank">http://exercise.about.com</a></span><br>
        <span><a href="http://www.webmd.com" target="_blank">http://www.webmd.com</a></span>
    </div>
</div>

MacGym_WebRole/Views/Workout/List.cshtml
@model ListModel
@{
    ViewBag.Title = "List";
}

<h2>List of Exercises</h2>

@foreach (var item in Model.Workouts)
{
    <hr>
    
    <div class="row">
        <div class="span2">
            @if(item.HasImage)
            {
                <a href="@Url.Action("Details", new { id = item.WorkoutID })">
                    <img src="~/Content/Images/Workouts/@(item.FirstImage)">
                </a>
            }
        </div>
        <div class="span10">
            <h4>@(item.Name)</h4>
            <p>@(Html.Raw(item.Description))</p>
            <p>@(Html.ActionLink("Details", "Details", new { id = item.WorkoutID }))</p>
        </div>
    </div>    
}
@*<div class="row">
    <div class="pagination pagination-centered span12">  
        <ul>  
        <li><a href="#">Prev</a></li>  
        <li class="active">  
            <a href="#">1</a>  
        </li>  
        <li><a href="#">2</a></li>  
        <li><a href="#">3</a></li>  
        <li><a href="#">4</a></li>  
        <li><a href="#">Next</a></li>  
        </ul>  
    </div>  
</div>*@